services:
  app:
    container_name: portfolio-nuxt
    build: .
    ports:
      - "3000:3000"
    working_dir: "/src"
    volumes:
      - ./:/src:cached
      - node_modules:/src/node_modules
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules:
